env:
  browser: true
  es2021: true
  node: true
globals:
  window: true
  React: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - xo
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  { object-curly-spacing: [error, always], react/no-unescaped-entities: off }
